package com.dsideal.jeef.model;

import com.dsideal.jeef.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config();
}
