package com.dsideal.jeef.model;

import com.dsideal.jeef.model.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
	public static final Dictionary dao = new Dictionary();
}
