package com.dsideal.jeef.model;

import com.dsideal.jeef.model.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource();
}
