package com.dsideal.jeef.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSystemName(java.lang.String systemName) {
		set("system_name", systemName);
	}

	public java.lang.String getSystemName() {
		return get("system_name");
	}

	public void setNavigationType(java.lang.String navigationType) {
		set("navigation_type", navigationType);
	}

	public java.lang.String getNavigationType() {
		return get("navigation_type");
	}

}
