package com.dsideal.jeef.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}

	public java.lang.String getLoginName() {
		return get("login_name");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	public void setDisabled(java.lang.Integer disabled) {
		set("disabled", disabled);
	}

	public java.lang.Integer getDisabled() {
		return get("disabled");
	}

	public void setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
	}

	public java.lang.Integer getDeleted() {
		return get("deleted");
	}

	public void setLoginTimes(java.lang.Integer loginTimes) {
		set("login_times", loginTimes);
	}

	public java.lang.Integer getLoginTimes() {
		return get("login_times");
	}

}
